// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0jqbKqcmnlfUVVSvfJR7CZG8qR6MiWfc',
    appId: '1:850197613162:web:0dd3ae02f74ea71ba59813',
    messagingSenderId: '850197613162',
    projectId: 'demoappcmru',
    authDomain: 'demoappcmru.firebaseapp.com',
    storageBucket: 'demoappcmru.firebasestorage.app',
    measurementId: 'G-D0H5HG2YZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnvfOiRtDt5lAMvubnfZij88jH9lETMt0',
    appId: '1:850197613162:android:43ae5ba67fd20627a59813',
    messagingSenderId: '850197613162',
    projectId: 'demoappcmru',
    storageBucket: 'demoappcmru.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzh6nBbgg0y6B2BllDKx7NCGEF0L0yW0M',
    appId: '1:850197613162:ios:0fee0a6ef115fde6a59813',
    messagingSenderId: '850197613162',
    projectId: 'demoappcmru',
    storageBucket: 'demoappcmru.firebasestorage.app',
    iosBundleId: 'com.example.binsortNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzh6nBbgg0y6B2BllDKx7NCGEF0L0yW0M',
    appId: '1:850197613162:ios:0fee0a6ef115fde6a59813',
    messagingSenderId: '850197613162',
    projectId: 'demoappcmru',
    storageBucket: 'demoappcmru.firebasestorage.app',
    iosBundleId: 'com.example.binsortNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0jqbKqcmnlfUVVSvfJR7CZG8qR6MiWfc',
    appId: '1:850197613162:web:327f65599da8b0f8a59813',
    messagingSenderId: '850197613162',
    projectId: 'demoappcmru',
    authDomain: 'demoappcmru.firebaseapp.com',
    storageBucket: 'demoappcmru.firebasestorage.app',
    measurementId: 'G-SBD8LT96YT',
  );
}
